### ISSUE TITLE
Can't compile on ESP8266 boards

### ISSUE THREAD

**Issue by sindudas** [VaSe7u/LiquidMenu#1]
.../Documents/Arduino/libraries/LiquidMenu/src/LiquidLine.cpp: In member function 'bool LiquidLine::attach_function(uint8_t, void (_)())':
.../Documents/Arduino/libraries/LiquidMenu/src/LiquidLine.cpp:37:21: error: cast from 'LiquidLine_' to 'uint16_t {aka short unsigned int}' loses precision [-fpermissive]
  print_me((uint16_t)this);
                     ^
.../Documents/Arduino/libraries/LiquidMenu/src/LiquidLine.cpp: In member function 'bool LiquidLine::set_focusPosition(Position, uint8_t, uint8_t)':
.../Documents/Arduino/libraries/LiquidMenu/src/LiquidLine.cpp:51:21: error: cast from 'LiquidLine*' to 'uint16_t {aka short unsigned int}' loses precision [-fpermissive]
  print_me((uint16_t)this);

**Comment by VasilKalchev** [comment]
It should be fixed now.

**Comment by sindudas** [comment]
Now it don't compile again but different error message:

xtensa-lx106-elf-gcc: error: libraries\LiquidMenu\LiquidMenu.a: No such file or directory
exit status 1

**Comment by TyIsI** [comment]
@sindudas your error is due to lack of support of the dot_a_linkage flag in library.properties by the ESP8266/ESP32 builder/compiler. Changing dot_a_linkage to false in your local copy of library.properties will likely fix your problem.

@VaSe7u FYI
