### ISSUE TITLE
Wrong `DataType::CHAR_PTR` cast

### ISSUE THREAD

**Issue by nfhktwrbq** [VaSe7u/LiquidMenu#12]
In class liquidLine incorrect cast for char pointer:
`char* variable = *reinterpret_cast<char**>( const_cast<void*>(_variable[number]) );`

correct variant is:
`char* variable = const_cast<char*>(reinterpret_cast<const char *>(_variable[number]));`

**Comment by VaSe7u** [comment]
Thank you, @nfhktwrbq.

**Comment by nlurkin** [comment]
Hi, 
I am facing the same issue here. If i use the second variant it works correctly. I see that you implemented it and then reverted a few months later. Any reason why the "correct variant" was not correct?

**Comment by VaSe7u** [comment]
Hello nlurkin,

I reverted it because the examples were using a different way of handling dynamic text. But this way really is better and is now re-reverted.
