### ISSUE TITLE
LiquidLine Pointer not Passing

### ISSUE THREAD

**Issue by lonestar1** [VaSe7u/LiquidMenu#18]
Hi Vasil,

I'm having issues passing a simple string pointer to LiquidMenu. I've found I get odd characters sometimes even in your example files where a string is being passed such as the * in H_system_menu. It's like it's pointing to the wrong memory location.

Here's my simple test. If you pass a variable directly (the commented one that says "this works") it seems to work ok.

It's probably a silly mistake on my part somewhere...

Cheers
Andreas
`// The LCD library
#include <LiquidCrystal.h>
// The menu wrapper library
#include <LiquidMenu.h>

// Pin mapping for the display:
const byte LCD_RS = 8;
const byte LCD_E = 9;
const byte LCD_D4 = 4;
const byte LCD_D5 = 5;
const byte LCD_D6 = 6;
const byte LCD_D7 = 7;
//LCD R/W pin to ground
//10K potentiometer wiper to VO
LiquidCrystal lcd(LCD_RS, LCD_E, LCD_D4, LCD_D5, LCD_D6, LCD_D7);

char str[5] = "MyStr";
char *testPointer = str;

// This works (comment out the above)
// char testPointer[] = "MyStr";

// Here there is not only a text string but also a changing integer variable.
LiquidLine testLine(0, 0, "TestPtr: ", testPointer);
LiquidScreen first_screen(testLine);

LiquidMenu menu(lcd);

void setup() {
  Serial.begin(115200);
  lcd.begin(16, 2);

  // This is the method used to add a screen object to the menu.
  menu.add_screen(first_screen);
}

void loop() {
  menu.update();
  delay(500);
}`

**Comment by VaSe7u** [comment]
Your code is fine. If you have downloaded the library from the main page, downloading release [1.3.0](https://github.com/VaSe7u/LiquidMenu/releases) should fix the problem.
