### ISSUE TITLE
Snprintf prints jibberish

### ISSUE THREAD

**Issue by Fettkeewl** [VaSe7u/LiquidMenu#27]
**Describe the bug**
Part of me hopes this is a bug and not a lack of my own coding skills :P!
Im trying to preformat a char array so I can have it look the way I want before
printing it to the screen.

Using snprintf I can format my output and display it in Serial. I have used this way of formatting char strings before the use of liquidmenu to print text the way I want it on an LCD. With liquidmenu I get trash characters displayed.

**To Reproduce**
Try code below

**Screenshots**
![Serial](https://user-images.githubusercontent.com/25577040/55664587-a0258a00-5830-11e9-8b93-3f86945e61d9.PNG)
![20190406_055214](https://user-images.githubusercontent.com/25577040/55664588-a0258a00-5830-11e9-8e5e-b18c4e747c6d.jpg)

**Related code**
```
char txtbuffer[17] = "Empty";
LiquidLine test(0, 0, txtbuffer);
LiquidScreen testS(test);

void setup() {
  Serial.begin(9600);
  setupEncoder();
  setupMenu();
  
  Serial.println(txtbuffer);
  snprintf(txtbuffer, 17, "BUFF: %s", "test");
  Serial.println(txtbuffer);
  menu.add_screen(testS);
  menu.update();
  
}

```

**Version of the library**
1.4.0

Edit:

This is what I am aiming for, as an "timeout/standby" display, to give a hint of what I'm trying to accomplish
![image](https://user-images.githubusercontent.com/25577040/55664690-913fd700-5832-11e9-8004-920b26ad5bdb.png)

**Comment by VaSe7u** [comment]
What is the output of `txtbuffer` on the display before formatting it with `snprintf(...)`? The `LiquidLine` object uses pointers to char arrays instead of char arrays directly (even though they are similar), take a look at the examples `C_functions_menu` and `D_buttons_menu`.

I think that the `size` argument of `snprintf(...)` should be 16.

**Comment by Fettkeewl** [comment]
**First:** according to this http://www.cplusplus.com/reference/cstdio/snprintf/
size should be 17 because the output string is 17-1 due to null terminating character

I tried this below, before snprintf the screen is just blank, after snprintf I get jibberish.
All serial.prints perform normally

```cpp
char txtbuffer[20] = "Empty";
LiquidLine test(2, 0, txtbuffer);
LiquidScreen testS(test);


void setup() {
  Serial.begin(9600);
  setupEncoder();
  setupMenu();
  menu.add_screen(testS);
  menu = testS;  
  Serial.println(txtbuffer);
  menu.update();
  delay(5000);
  snprintf(txtbuffer, 17, "BUFF: %s", "test");
  Serial.println(txtbuffer);
  //menu.add_screen(testS);
  menu.update();
  delay(10000);
}
```

however I tried this aswell and it atleast did output the first Char.
"E" then "B" after snprintf
```cpp
char txtbuffer[20] = "Empty";
LiquidLine test(2, 0, txtbuffer[0]);  //<--------- difference
LiquidScreen testS(test);


void setup() {
  Serial.begin(9600);
  setupEncoder();
  setupMenu();
  menu.add_screen(testS);
  menu = testS;  
  Serial.println(txtbuffer);
  menu.update();
  delay(5000);
  snprintf(txtbuffer, 17, "BUFF: %s", "test");
  Serial.println(txtbuffer);
  //menu.add_screen(testS);
  menu.update();
  delay(10000);
}

**Comment by VaSe7u** [comment]
> "I tried this below, before snprintf the screen is just blank, after snprintf I get jibberish."

`char txtbuffer[20]` is set to `"Empty"`. If the screen doesn't print "Empty" (i.e. displays nothing or jibberish), this means that `txtbuffer` isn't working before `snprintf(...)`. This is expected, because the `LiquidLine` object uses pointers to char arrays, not char arrays directly, it doesn't work the same way as `Serial.print(...)` or `lcd.print(...)`.
You should have a separate char pointer that points to `txtbuffer` and use that pointer as an argument to `LiquidLine`'s constructor (examples: `C_functions_menu` and `D_buttons_menu`).

**Comment by Fettkeewl** [comment]
Thank you, your suggestion worked great. Although I do not understand it.
textbuffer array is a pointer to the address of the first value of the array in memory, assigning this address to a pointer makes it usable, but using the address directly does not? How weird..

**Comment by VaSe7u** [comment]
It is weird, the library is a little hacky. It manually recognizes the data type and stores the address of the variable in a void pointer, then when printing - the variable is casted back. Take a look at `bool LiquidLine::add_variable(T &variable)`, `void LiquidLine::print(DisplayClass *p_liquidCrystal, bool isFocused)` and `recognizeType.cpp` if you want to know how it works.

Basically, for dynamic text, you can use a `char*` that can be pointed to different char arrays. And for constant text, `const char*` directly.
