### ISSUE TITLE
is_callable make an undesired call_function 

### ISSUE THREAD

**Issue by luzz94** [VaSe7u/LiquidMenu#43]
**Describe the bug**
when i use the is_callable function it make also an call_function with the same id

**To Reproduce**
I was testing out the "H" example in order to use UP/DOWN buttons to navigate through the menu and then, if the focused line had a incremental/decremental function attached (using is_callable function), using the SELECT button i enable the UP/DOWN button in order to modify the value. Instead the SELECT button make another action (ex. back buttons)

**Possible solving solution**
The problem seems to be on the "LiquidSystem.cpp" where:

bool LiquidSystem::is_callable(uint8_t number) const {
return _p_liquidMenu[_currentMenu]->call_function(number);
}

instead of 

bool LiquidSystem::is_callable(uint8_t number) const {
	return _p_liquidMenu[_currentMenu]->**is_callable**(number);
}

Now the code seems to be work

**Comment by VaSe7u** [comment]
Thanks.
